### ISSUE TITLE
Sidebar admin options visible on Character screen.

### ISSUE THREAD

**Issue by hderp886** [eveseat/seat#130]
To replicate:

Impersonate a character with zero roles.
Go to Characters > All Characters > Select a Character.

Sidebar items for Seat Api / Slackbot (if installed) are visible despite having sidebar perms set.

**Comment by warlof** [comment]
confirmed

**Comment by leonjza** [comment]
Thanks for the report @hderp886 ! This is definitely a bug. However, it seems to only reveal the menu item and not allow you to actually view the content. Can you confirm that this is the case your side as well?

**Comment by hderp886** [comment]
@leonjza Confirmed!

No apparent security risk.

**Comment by leonjza** [comment]
Thanks!

**Comment by warlof** [comment]
Hello hderp886, we've miss a bit this issue but we're no longer able to reproduce it using latest package. Can you tell use if it has been solved or is it still open ?

**Comment by leonjza** [comment]
I think this is still reproducible. Bug might be caused by how owned keys are handled.

**Comment by warlof** [comment]
Confirmed according to our yesterday talk it's related to the way Acl are granting wildcard permission.

I'll write test case later this week.

**Comment by MisteryMan** [comment]
I've just updated our installation, we have the same bug still at this date.

**Comment by warlof** [comment]
I'm almost sure it's related to the way we're handling ACL on owning stuff.

https://github.com/eveseat/web/blob/master/src/Acl/AccessChecker.php

If the content is matching to an owning one (ie : character or corporation like it's the case when you go on your character page), we're set the granted permission to wildcard (*).

It's working well for simple access, but it's not the case for granularity. Yes, when you go on your own stuff, you've access to everything BUT, everything related to this stuff :
mean, if you're on a character stuff, we shouldn't grant corporation permission or anything else

It's explaining why you get access to system permission.

Finally, this issue is not only true for character, but as explained, for corporation aswell.

**Comment by leonjza** [comment]
Fixed in the latest web package via commit https://github.com/eveseat/web/commit/829b93bf1e8db4841b4544e98dc7d4678e46609a.
