### ISSUE TITLE
An unknown failure in Seat\Eveapi\Jobs\CheckAndQueueKey occured

### ISSUE THREAD

**Issue by Raikia517** [eveseat/seat#135]
- **Problem**: Lots of failed jobs with an "Unknown Failure"
- **Expected**:  No failed jobs or at least a better error message
- **Explanation**: I recently imported over 2500 API keys and never had this issue before having a lot of API keys.  I currently run supervisor with 9 workers, so the queue never really ends before more are added again to the queue.  Is there a better optimization here I am missing?  The API imports go surprisingly slow for even just 1 API key when I would think it would be at most 10 seconds for all the API calls it needs.
- **Logs / Screenshots / Proof**:
  Diagnose Output:  http://pastebin.com/d4aKg8SN
  Laravel.log: http://pasted.co/0f82761a (not pastebin because its too big)
  
  _The more information you give the better!_
- **Version Info**: _PHP Version, SeAT Version, Operating System etc._

```
+---------------+---------------+---------------+
| Package Name  | Local Version | Latest Github |
+---------------+---------------+---------------+
| Api           | 1.0.13        | 1.0.13        |
| Console       | 1.0.16        | 1.0.16        |
| Eveapi        | 1.0.17        | 1.0.17        |
| Notifications | 1.0.4         | 1.0.4         |
| Web           | 1.0.30        | 1.0.30        |
| Services      | 1.0.22        | 1.0.22        |
+---------------+---------------+---------------+
```

OS: Ubuntu 16.04

**Comment by warlof** [comment]
Can you provide few job exception detail ?
They are available in failed job list > view full

But first, according to your log, few of them failed because of :
- wrong access on the key (403 result)
- curl issues (should monitor a bit your server, but it could be due to bandwidth, bad network or high cpu load)

Still according to your log and the key amount, you should increase the worker number (9 is definetely not enough)

Count the first number of `job for Api Scheduler and owner %d already exists` and divide with `9`. It will show you the number of job fire every cycle.

**Comment by leonjza** [comment]
Currently, this is an expected behavior introduced in https://github.com/eveseat/eveapi/commit/bd3e928 to prevent your jobs from getting stuck.

**Comment by leonjza** [comment]
To add to this, unfortunately in Laravel 5.1, the *actual* exception is not passed to the `failed()` method, hence the relatively generic error message.

**Comment by drkthunder02** [comment]
The problem is you are running too many jobs and not enough workers.  If your queue is overlapping like mine was previously, I modified the default poll time to be a bit longer, but added more workers.  Currently, my system is running 12 workers right now, and with enough RAM you should easily be able to get up to 20.

**Comment by leonjza** [comment]
This generic error is a thing of the past as SeAT 2.0 was upgraded to Laravel 5.3 that actually passes the exception thrown into the `failed()` method!
