### ISSUE TITLE
Mail Timeline is extremely slow

### ISSUE THREAD

**Issue by Raikia** [eveseat/seat#172]
I'm not sure if its a lack of an index or what, but the Mail Timeline page is extremely slow when you have a lot of data in the database.

![img](http://i.imgur.com/BUK4oZ3.png)

It takes anywhere from 20 - 40 seconds to load.

Also the footer should say "19.311 s" instead of "ms" since its in seconds :-P

**Comment by leonjza** [comment]
Whats is the output of the following queries in your instance?

```
select count(*) from character_mail_messages;
```
and
```
select count(*) from character_mail_message_bodies;
```

**Comment by Raikia** [comment]
![img](http://i.imgur.com/m0HqS9D.jpg)

**Comment by leonjza** [comment]
Hmm that doesnt seem like a large amount of data at all. What I find particularly interesting is the time it took just to count the rows vs mine.

<img width="482" alt="screen shot 2017-01-06 at 6 48 46 am" src="https://cloud.githubusercontent.com/assets/1148127/21707920/5eabee3c-d3dc-11e6-90d3-0dcff828bb76.png">

On the web interface, this box loads the mail timeline in ~2.5s

<img width="531" alt="screen shot 2017-01-06 at 6 50 46 am" src="https://cloud.githubusercontent.com/assets/1148127/21707931/7bb6a85a-d3dc-11e6-89d5-82dfe6975069.png">

Could you report back on your servers specs and load average? For reference, here is the load average on my 2CPU, 2GB RAM, Non-SSD VPS that loaded the mail timeline in 2.5s

<img width="576" alt="screen shot 2017-01-06 at 6 51 41 am" src="https://cloud.githubusercontent.com/assets/1148127/21707948/ab51560a-d3dc-11e6-856f-aec2ddf543ca.png">

**Comment by Raikia** [comment]
2CPU, 2GB RAM DigitalOcean droplet.  Completely fresh install (not the same server as my original screenshots):

![img](https://vgy.me/RJ9Aa5.png)

Sometimes it's even gotten to 55 seconds!

![img](https://vgy.me/9cdnQ2.png)

![img](https://vgy.me/5ZEnqW.png)

Any suggestions?  I have 7 workers currently and about 2000 valid API keys....  Do you have any non-standard MySQL tweaks?  Mine is just 100% base install.  I literally created this droplet fresh tonight, followed your installation instructions, and threw all the APIs in it.  Same problem as my original server.

**Comment by Raikia** [comment]
BTW same with the dashboard:

![img](https://vgy.me/as5DDD.png)

It honestly looks like everywhere where mail messages are called is super slow

**Comment by Raikia** [comment]
The query that its running that is super slow is:

    select * from `character_mail_messages` inner join `character_mail_message_bodies` on `character_mail_messages`.`messageID` = `character_mail_message_bodies`.`messageID` inner join `account_api_key_info_characters` on `character_mail_messages`.`characterID` = `account_api_key_info_characters`.`characterID` inner join `eve_api_keys` on `eve_api_keys`.`key_id` = `account_api_key_info_characters`.`keyID` group by `character_mail_messages`.`messageID` order by `character_mail_messages`.`sentDate` desc limit 25 offset 0

**Comment by leonjza** [comment]
Ow. A load avg of 7.4 will probably make a lot of things pretty slow and is definitely a contributing factor to the experience. Effectively, the box has 7 times more work to do than it can actually handle (rough estimate ofc!)

Debugging this, I think there are two major things at play here.

First of all, the query in question _could_ probably be optimized, so I am open to any suggestions to do this. Reality though is, under normal conditions it shouldn't be as slow as you are experiencing here.

Secondly, 2k API's is quite a chunk of work to go through. In my similarly specced (non-SSD) server, ~400 keys can take ~15 to 20 minutes to process (depending on the CCP api performance etc) with 6 workers. While the update work is busy doing its thing, the web UI does take a bit of a performance hit as both the workers and the web UI live on the same box (this is expected). I suspect that in your case, with 2k jobs being dropped into the queue every hour, that queue probably **never** comes to rest. In fact, it probably keeps falling behind further and further.

Simply increasing the worker counts isn't really an option either as it has diminishing returns on performance due to various factors. So what can be done? There are a few options.

## stop the queue updaters
Start by stopping the queue workers after a period of time when there is some data in the database. When you are sure they are stopped, **ensure** the load is back down to below 1 and check what the web UI loading times is then.

## increase the queue initiator time
Considering the number of keys you are talking of, the first thing I would do is increase the schedule between keys being queued for update. Browse to _Settings_ -> _Schedule_ and remove the `eve:queue-keys` command and re-add it with an increased schedule of maybe every 3 hours.

## consider scaling hardware a bit
MySQL being the biggest component, but in the end, the hardware will only be able to handle so much. I am not sure if you have a SSD droplet, but that will most probably also increase the performance tremendously. I wrote a small docs about some ideas a while back here: [http://seat-docs.readthedocs.io/en/latest/admin_guides/scaling_seat/](http://seat-docs.readthedocs.io/en/latest/admin_guides/scaling_seat/)

Lastly, there a few people on Slack with insanely large SeAT installations. I suggest you join us there and lets have an actual conversation about this ;)

[http://seat-docs.readthedocs.io/en/latest/contact/#slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack)

**Comment by Raikia** [comment]
I've changed the queueing time to be every 3 hours (it looks like my queue finishes approximately 1 hour and 10 minutes after queueing, so it was definitely overrunning itself).  While the queue is processing, its pretty slow, but once the queue finishes, I get quicker response times (2 second rendering times). So that is definitely the problem.  I think its just a hardware limitation and not a SEAT bug, I appreciate your extremely helpful response though.  This issue can probably be closed

**Comment by leonjza** [comment]
Awesome thanks for the feedback!
