### ISSUE TITLE
Assets In Citadels

### ISSUE THREAD

**Issue by leonjza** [eveseat/seat#174]
* **Problem**: Assets in citadels dont appear in the assets views.
* **Expected**: An asset entry from a perspective entities assets view that has assets in a citadel.

It appears as though the assets endpoints do show the assets in citadels and SeAT does store it in the database, however, the `locationID` is not something that can be resolved at the moment. For this reason, the case statement that tries to figure out the station name against the sde and sov tables returns nothing for those entries, resulting in citadels assets entry not returning.

Ref code: https://github.com/eveseat/services/blob/master/src/Repositories/Corporation/Assets.php#L57-L77

**Comment by IvandaNothabeer** [comment]
Assets in citadels are only returned if the XML request is "flat".

This means that the hierarchy structure of the XML is lost and every item is returned with an individual locationID, which may be one of many possibilities, including stations, systems etc but is much more likely to be the itemID of the parent container. Searching for this parent itemID can be time consuming as there are multiple places to look and you must do this for every item in the asset list. ( which is why the hierarchical XML data is so much more useful )

The locationID for an asset inside a citadel is the itemID of the citadel which may or may not be known. If the asset is located in a corp or alliance owned citadel then the itemID probably IS known and can be searched for in the asset list of the owning corporation.

Ultimately, this is a problem that CCP need to fix. Unfortunately they probably aren't going to.

**Comment by warlof** [comment]
It seems to be improved on esi, but the api is still to teeny in order to replace xml api with it.

**Comment by leonjza** [comment]
I have build the client library SeAT will be using to access ESI. Source here: https://github.com/eveseat/eseye. Its a standalone library that is not tied to SeAT and can be used in any PHP project.

Once this library is included into SeAT core and the ESI endpoints become _usable_, then there will be a big project to figure out how Authenticated SSO & ESI will work in SeAT. Long story short, this will fix this issue too.

**Comment by leonjza** [comment]
3x fixed it!
