### ISSUE TITLE
Feature Request -> show expire time when check the API 

### ISSUE THREAD

**Issue by SNIPER722** [eveseat/seat#205]
Hello, 
Is that possible to add a expire time when check the API before adding it? 
Since some Corp. require a never expire API. 

Instead of add into the list and go through the list to find the expire time. when check the API show the expire time.

**Comment by leonjza** [comment]
Its totally possible, though I doubt this will land as the whole idea of expiring tokens will simply fall away with ESI.

**Comment by SNIPER722** [comment]
I totally agree with the expiring token will go away with ESI. But I don't believe ESI could get account status, It only provide the character you authenticated.

**Comment by warlof** [comment]
Esi will not be an option since both Crest and xml are currently discontinued and will be shutdown on few months.

Therefore, Seat will probably be freeze about XAPI implementation and will focus features development on esi migration.

During next month (shortly), only hotfix will be provided. New feature should most probably come with 3.x and its esi implementation.

On the board :
XAPI replaced by esi
Database structure improvement
Acl improvement
Further more :)

**Comment by SNIPER722** [comment]
Please add custom corn job tab(eg. 2hours/4hours/6hours option). please... (from a person who is too lazy to write corn job)
