### ISSUE TITLE
Upgrade to Laravel 5.5.* doesnt work

### ISSUE THREAD

**Issue by IvandaNothabeer** [eveseat/seat#221]
The latest commit changes the composer.json file in the seat root directory to use laravel 5.5.* (instead of 5.3.*) This does not work.

- If you try a Git Pull of this version then several dependencies are broken. Composer will only update if you revert the composer.json required laravel version to 5.3.*

- If you then try to update SeAT using Laravel version 5.5.*, ( by updating **ALL** the composer.json files in \vendor\eveseat\... to resolve dependency errors ) then you get a "class auth.email does not exist" and the application does not run.

**Comment by warlof** [comment]
Due to coming 3.x work, repository policy has changed in some way
- master become the dev branch
- Major.x become the stable major version (ie : 2.x)

Therefore, from now, if you want to clone project from source, you had to clone from the targeted version branch. (let's say 2.x)

For standard setup, normaly, `composer create-project eveseat/seat seat --no-dev` should provide you the latest stable version.

**Comment by leonjza** [comment]
Checkout the 2.x branch (or the latest tag). The stuff in master is not meant for production and is currently the slow progress being made for v3.x

**Comment by IvandaNothabeer** [comment]
Sweet. Thankyou
