### ISSUE TITLE
Testing SeAT 3.0 - People Group

### ISSUE THREAD

**Issue by herpaderpaldent** [eveseat/seat#243]
* **Problem**:  People-Groups not working

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'Seat\Eveapi\Models\Eve\ApiKey' not found"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in /var/www/seat/packages/eveseat/services/src/Repositories/People/PeopleRepository.php:94
```

* **Expected**: Overview of the Character Groups. Maybe linked to the multiple Character functionality? 
* **Logs / Screenshots / Proof**: 

![image](https://user-images.githubusercontent.com/6583519/38112887-9731adc8-33a3-11e8-8a3f-87ea008d3af4.png)

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._

**Comment by leonjza** [comment]
Tagging this to triage, but old style people groups are going to be nuked.

**Comment by benthompson0** [comment]
I just want to confirm, the new way you are matching people where every character has a corresponding user and you match them with groups is the way things will continue down the track?

I am working on a updated version of a package that helps setup Discord access for our members and we used people groups to work out the main character but it seems since every character is a user we can't work out who the main is anymore? I even noticed in the user_settings table that every new user had main_character_name/main_character_id set to itself.

**Comment by warlof** [comment]
@benthompson0 that will be automatically handled as longer as the user will add character himself.
In 3.x; a character is a full user. All of them are linked by a group

you'll find what you need into
`users`, `groups`, `group_user`

**Comment by leonjza** [comment]
Groups are automatically assigned now based on the "linking" they do (via the plus from the profile dropdown (which i might remove) or "link character" from the profile page). Still need to fix up the "main character" setting.

**Comment by leonjza** [comment]
On top of that, in terms of ACL groups, those will bolt on to the automatic groups we have.

**Comment by benthompson0** [comment]
thanks for the clarification @warlof and @leonjza
