### ISSUE TITLE
Make this available to run via Captain DuckDuck (docker-swarm heroku like tool)

### ISSUE THREAD

**Issue by Timmeey** [eveseat/seat#325]
I would like to run SeAT in an environment (docker swarm) that is managed by "Captain DuckDuck"(https://github.com/githubsaturn/captainduckduck). Unfortunately my inside knowledge/understanding of docker/docker-compose is not enough to translate the docker-compose file to the appropriate captain-definition files as are required by captain duckduck

Request:
Provide files and documentation how to run SeAT via captain duckduck.

Thank you :-)
It would be really awesome to be able to integrate this into our already running infrastructure.

**Comment by warlof** [comment]
As per v4, I try to center our scripts/docs to the project itself rather than a giant generic wiki.

It appears we've lost a bit of focus by covering every single ways to deploy SeAT, even covering server installation which is not the project goal and increase needs of maintenance. 

I can recommend you to pass on our slack if you need to exchange on the topic. I know we got peeps with lot of docker skills and furthermore.
