### ISSUE TITLE
Corp/Alliance names not showing, showing ID's instead

### ISSUE THREAD

**Issue by GoldenCoins** [eveseat/seat#339]
![image](https://user-images.githubusercontent.com/13414010/40455534-4b737886-5ee5-11e8-95ed-245bb9b607b1.png)

For some reason seat in various places is only showing corp and alliance ID's not names.

When looking at corporation tracking it also does the same but for member characters.
Is there a way to fix this?

**Comment by herpaderpaldent** [comment]
This is probably a dublication of https://github.com/eveseat/seat/issues/249 

Root of this may be the missing writing permission on the logfile for eseye

>if you are using apache you need to realize www-data is not able to access the seat if he does not own it or have permission to RL from it
2 solution : 1. set permission to 777 (unsecure) 2. let virtual host run as the user own director (deafult seat)

**Comment by leonjza** [comment]
Hey,

Thanks for reporting this. At first glance this does not look like a code related issue (which are the only ticket types we would like to track here.) Please join us on Slack so that we can help you there in the #support channel.

For Slack invites, please see: https://eveseat.github.io/docs/about/contact/

Please remember to come back and close this issue when you are done :)

**Comment by leonjza** [comment]
Think I fixed this. Update your docker install with: https://eveseat.github.io/docs/guides/admin/docker/#performing-updates
