### ISSUE TITLE
Can't install on ubuntu due to MYSQL issue

### ISSUE THREAD

**Issue by GoldenCoins** [eveseat/seat#340]
Upon reaching the stage of installation where you have to run 
`sudo -H -u root bash -c 'php /var/www/seat/artisan migrate'
`

I get this error back:
![image](https://user-images.githubusercontent.com/13414010/40457157-da941fd2-5eec-11e8-9b38-19d6f1a92584.png)

I've followed all the instructions to the letter, but can't get past this. I've flushed privileges, and granted all etc etc. But I have no idea how to fix this.

please can someone help?

**Comment by warlof** [comment]
https://eveseat.github.io/docs/guides/installation/manual_installation/ubuntu/

**Comment by herpaderpaldent** [comment]
What guide for installation have you used @GoldenCoins ? your cited code does not exist in the manual installation guide for docker which warlof had you referenced ...

**Comment by leonjza** [comment]
Hey,

Thanks for reporting this. At first glance this does not look like a code related issue (which are the only ticket types we would like to track here.) Please join us on Slack so that we can help you there in the #support channel.

For Slack invites, please see: https://eveseat.github.io/docs/about/contact/

Please remember to come and close this issue when you are done.
