### ISSUE TITLE
Mumble auth service 

### ISSUE THREAD

**Issue by zuiji** [eveseat/seat#370]
Hej seat team.
I wish you could build a plug in that kick /delete people from mumble if they leave Corp or alliance.

**Comment by evidex** [comment]
This could be nicely done by integrating with https://gitlab.com/allianceauth/allianceauth, using Seat as the auth backend. Alliance Auth already supports integration with mumble, forums, discord etc

**Comment by warlof** [comment]
Closing this issue as it will not be addressed by core.

Still related to bridge, I've built Slack, Discord and Teamspeak bridges:
 - http://github.com/warlof/slackbot/
 - http://github.com/warlof/seat-discord-connector/
 - https://github.com/warlof/seat-teamspeak
 - https://github.com/warlof/seat-connector

Furthermore, since eveseat/web@3.0.10, you got access to extra events related to groups assignation and removal.

Also, I know that @wfjsw worked on something related to mumble.

**Comment by wfjsw** [comment]
https://github.com/wfjsw/seat-mumble-connector

This is a source code snapshot of Mumble plugin currently running on my instance.

Note that I cannot provide any kind of support nor documentation on this plugin, so you'll have to dig into the source code and and glue these part together on your own.
