### ISSUE TITLE
Cannot Assign Roles/Group

### ISSUE THREAD

**Issue by Derjyn** [eveseat/seat#408]
It's broken.  See image.  I have created groups, assigned roles in the group, associated users, and so on.  None of it gets applied to users/characters, and when editing a user, the drop-down box is broken (simply displays "No results found").

![capture](https://user-images.githubusercontent.com/648059/43041617-87c91242-8d1a-11e8-970f-b955a451b775.PNG)

**Comment by warlof** [comment]
You simply can't create group as group are handled by the system.

What you've created is role into which you put permission.

To assign them, you have to go into the role you've created from access management.

**Comment by Derjyn** [comment]
Okay, then instead of broken, how about this: the UX/UI isn't intuitive, and doesn't function as one might expect.  Which is basically a longer way of saying "broken".  But yes, more meaning.

How is this nested, in a tree form?  Groups can have roles, roles can belong to a group, character can have roles?  I assume that a role is created, which then has permissions defined.  Then a group can contain multiple roles?  And finally a character can be assigned to a group, and the roles are then assigned?

I'm slightly familiar with RBAC and ACL design and theory, but am having a hard time understanding the purpose of groups in SeAT, or why that drop-down box and assigning group option was there (albeit, with no possible groups to do so).  Sorry, I'm just not finding any documentation on that.

There isn't any particular thing I'm attempting to do- just getting to know SeAT from the inside out.

Thanks for your time!

**Comment by herpaderpaldent** [comment]
I am having troubles with your screenshot. It appears that you took it at `/configuration/users/edit/{id}` ... however you have missing translation: `seat_group_to_assign` which is not possible with SeAT 3.0.x since at least 1 group exists and is shown here ... 

You are trying to achieve smth in a not vanilla SeAT instance. 

Furthermore: You are trying to assing the user you have selected to a user_group. (@warlof remember the plurality discussion which we had this week?) This user_group is only about how multiple user/characters are logically combined. 
This has nothing to do with roles, or SeAT_groups (my plugin)
