### ISSUE TITLE
ACL - all permissions for character added still can´t see anything

### ISSUE THREAD

**Issue by dkrotil** [eveseat/seat#440]
We trying to setup recruitment role, I added all permissions which name begins with **character.** and even that we getting errors, when trying to access character like this

`Request to character/view/sheet/96085700 was denied by the characterbouncer. The permission required is character.sheet.`

SeAT Api
        Installed: v3.0.1

SeAT Console
        Installed: v3.0.1

SeAT Eveapi
        Installed: v3.0.3

SeAT Notifications
        Installed: v3.0.1

SeAT Web
        Installed: v3.0.5

SeAT Services
        Installed: v3.0.1

**Comment by warlof** [comment]
Without your role setup, we can't assist.

**Comment by dkrotil** [comment]
**Permissions** 

Character.skills 		
People.view 		
Character.assets 		
Character.bookmarks 		
Character.calendar 		
Character.channels 		
Character.contacts 		
Character.contracts 		
Character.fittings 		
Character.industry 		
Character.intel 		
Character.jobs 		
Character.killmails 		
Character.list 		
Character.mail 		
Character.market 		
Character.mining 		
Character.notifications 		
Character.pi 		
Character.research 		
Character.standings 		
Character.sheet 		
Character.journal 		
Character.transactions 		
Search.characterAssets 		
Search.characterContactLists 		
Search.characterMail 		
Search.characters 		
Search.characterSkills 		
Search.characterStandings 

**Affiliations**

All Corpotations

**Comment by dkrotil** [comment]
Not sure what you mean, in affiliation are all corporations. 
I haven´t posted Groups, because without to linking to someone it will not work, this is obvious.

**Comment by warlof** [comment]
affiliation are working per scope
`character.*` permission is `character` and concerned by :
 - character affiliation
 - all characters affiliation

`corporation.*` permission is `corporation` and concerned by :
 - corporation affiliation
 - all corporations affiliation

also, you need to assign the roles to users. Otherwise, they will not get the role and its attached permission.

-> https://eveseat.github.io/docs/admin_guides/role_based_access_control/

**Comment by leonjza** [comment]
Hey,

Thanks for reporting this. At first glance this does not look like a code related issue (which are the only ticket types we would like to track here.) Please join us on Slack so that we can help you there in the #support channel.

For Slack invites, please see: https://eveseat.github.io/docs/about/contact/

Please remember to come back and close this issue when you are done :)
