### ISSUE TITLE
Difference in token validity between user list and corp tracking

### ISSUE THREAD

**Issue by mparadies** [eveseat/seat#488]
For multiple characters, the ESI token validity identifier differs between user list and corp tracking pages.

**Comment by herpaderpaldent** [comment]
Ok so, i said on Slack, i can confirm this error. Probably something in the leftjoin is wrong. As i am refactoring the datatables of corporation next i'll update this. 

@mparadies is actually on of my corporation mates which showed me this error and i'll add some details to it. 

For anyone reading this: **CorpTracking might give false informations, /configurations/users is accurate**

Tinkering one of the found inconsitencies:

```
>>> Seat\Web\Models\User::find(2113869023)->refresh_token
=> null
```
So this user does not have a refresh_token, however the CorpTracking query results in the following:

```
Seat\Eveapi\Models\Corporation\CorporationMemberTracking::where('corporation_member_trackings.character_id', 2113869023)->leftJoin('refresh_tokens', 'refresh_tokens.character_id', '=', 'corporation_member_trackings.character_id')->select('corporation_id', 'corporation_member_trackings.character_id', 'start_date', 'base_id', 'logon_date', 'logoff_date', 'location_id', 'ship_type_id')->selectRaw('case when isnull(token) then 0 else 1 end as key_ok')->get();
=> Illuminate\Database\Eloquent\Collection {#3491
     all: [
       Seat\Eveapi\Models\Corporation\CorporationMemberTracking {#3479
         corporation_id: 1184675423,
         character_id: 2113869023,
         start_date: "2018-03-05 18:26:00",
         base_id: null,
         logon_date: "2018-11-23 20:27:17",
         logoff_date: "2018-11-23 20:35:00",
         location_id: 1028832949394,
         ship_type_id: 670,
         key_ok: 1,
       },
     ],
   }
```

I'll refactor this using relations. instead of joins
