### ISSUE TITLE
[FR]: UI profile button improvement?

### ISSUE THREAD

**Issue by kwazulueve** [eveseat/seat#496]
* **Problem**: We run a Seat instance with 1500+ characters. One of the repeating user issues is they have trouble finding the buttons under the character name in the top right corner (Link/Switch character, Profile, Sign out). The character portrait is not a very intuitive button for people to click on, hence some keep asking.

To make things a bit more idiot proof, perhaps it would be an idea to move these buttons under the Home button under the left menu? As soon as someone logs into Seat, these options then would be visible. Another option would be to add something of menu symbol right next to the character portrait.

Thanks :)

Kwa

**Comment by herpaderpaldent** [comment]
i suggest not to implement this. 

Reason: I take what is facebook for 100

![image](https://user-images.githubusercontent.com/6583519/50111846-08c70780-023e-11e9-8f1b-80321116aae1.png)

**Comment by kwazulueve** [comment]
You are exactly proving my point, you click on the 'v' button that people recognize as a menu, not on your profile picture with a name (in your top left of the image) to look for menu options

**Comment by herpaderpaldent** [comment]
![image](https://user-images.githubusercontent.com/6583519/50115857-e1296c80-0248-11e9-8aaf-e127af60e426.png)

Sorry what i meant to say it is an UI pattern upper right brings up a contextual menu ....

**Comment by Crypta-Eve** [comment]
Correct me if I am wrong but your problem arises mostly due to feedback from users that they cannot find how to perform session functions (logout, link char etc.) and due to this you want to move the sessions related menu items over to the left and group them with the rest of the pages... And the problem you have with this feedback is that it takes away from your time.

Really to move session/account related items over to the left menu is not a great idea in terms of UI design as you are then grouping session information with user information. 

In all honesty if people are having trouble finding the menu under the character name, then changing to another icon next to it will likely make little difference. 

My suggestion is to create an image/guide which you can make available to all new members of seat which shows them how to login / link characters etc.

**Comment by kwazulueve** [comment]
1) Linking characters or profile do not ring as session functions to me, logging in and out yes.
2) The button could easily be made more clearly a button, whether it has a hover over, a 'V' next to the name/profile picture or adding/moving it under the Home menu option.

If a guide is required to click/find the logout button, well I am not sure what to say ....
Hint: Alliance Auth (yes we run that as well for a seperate group) does not have these issues, ie questions where to link characters, because it is right in the face when you login

**Comment by kwazulueve** [comment]
Yeah that would make it more obvious already ;)

Merry Christmas!
