### ISSUE TITLE
Pause Job when ESI sever offline

### ISSUE THREAD

**Issue by player7132** [eveseat/seat#510]
Every DT SeAT Generate lot of errors because server is down.
this might be helpful for Resorce saving things

**Comment by jediefe** [comment]
You could change the cron job in SeAT settings to not pull ESI at 11:00 ET.

**Comment by warlof** [comment]
Normally, jobs use server status changes in order to avoid such things. So except if jobs were already queued when the server is gone, it shouldn't occur.

**Comment by GoemFunaila** [comment]
I found problem. It must be job is queued exactly same time when server status check job.
so job queued before status check job is failed.

**Comment by warlof** [comment]
Job flow has been improved with SeAT 4.0.x using some middlewares.
Currently, when Tranquility appears to be down, exception are thrown - however, I think we can remove the job from queue if needed.

**Comment by benthompson0** [comment]
I would like this to stop throwing an exception - here are two ideas as I see it:
1. As suggested above, we silently drop the job in it can't be run at the time due to ESI down. The jobs should all be regularly scheduled so it would start again later.
2. We could leverage the Delayed Dispatch (https://laravel.com/docs/6.x/queues#delayed-dispatching) capability to automatically have the job rescheduled to run say 30 minutes later.

Thoughts?

**Comment by warlof** [comment]
Hi agree with the job dropping, give it a try.
When such case occurs, we have to log it though - just to keep a track.

However, I don't think we should delayed job. The scheduler will continue to work - so we may land in case were we have multiple batch pending in queue.
