### ISSUE TITLE
Feature Request people groups: Being able to minimize all and selected tables

### ISSUE THREAD

**Issue by nizzan** [eveseat/seat#58]
It'd be nice to be able to minimize all groups, so you don't get a huge page at all times.
This also goes for assets and such.

**Comment by leonjza** [comment]
On the people groups topic. With ESI going to be a thing, a lot of discussion is needed on how this is going to affect SeAT going forward.

With ESI, a user will log in, and you will only have a refresh token for that specific character they logged in with. A feature will be added to allow users to 'link' more characters by prompting them to login with those characters so that the refresh tokens can be stored.

This implies that people groups will most probably be an automated thing soon. 

Any more ideas/features that relate to this? Chip in here or on Slack!

**Comment by leonjza** [comment]
People groups have kind of fallen away in their current form in 3x. Getting a major facelift somewhere in a 3x version.
