### ISSUE TITLE
Need help setting up a new SeAT installation

### ISSUE THREAD

**Issue by Klistofklades** [eveseat/seat#589]
Okay, so I've been at this for a couple weeks now just going over documentation and various google posts that aren't exactly what I need... Set up a server, got seat working, tried to add the groups and discord interface packages, said I didn't have enough memory on the server, so now I get to start over again on a bigger VM. I still need to figure out how to set up the server so that I can host a forum and use https protocol. Wondering if anyone would be willing to sit down with me sometime to help me? I couldn't ever figure out how to get it to open seat on the seat.domain.com instead of www.domain.com either... Any help would be appreciated. Most of my time I spend with raw code (java and python mostly, though I've done a bit in c++) or actually playing the game, this was my first time messing with server settings, disabling root ssh logins, configuring firewalls, etc, etc. I'm in US eastern time zone.

I've been using Centos 7, but the VM I've been using can use pretty much anything.

I'll still check on here every day, but if anyone wants here is a discord server where I check things more often: https://discord.gg/KxwYnCs

**Comment by warlof** [comment]
Hi @Klistofklades 

Configuring a server isn't really the scope of that project. However, I'll give you a few information we have :
 - [configuring a SeAT host using nginx](https://eveseat.github.io/docs/installation/webservers/nginx/)
 - [configuring a SeAT host using Apache](https://eveseat.github.io/docs/installation/webservers/apache/#centos-installation)
- [installing web server using apache](https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-18-04)
- [installing web server using nginx](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04)

Since you installed SeAT using the installer tool, please remember you already have an existing configuration file. Also, the default http service used by the tool is nginx.

Also, keep in mind that Digital Ocean got a giant wiki regarding server configuration and most of them got a really good quality.
