### ISSUE TITLE
Improve scheduler flexibility

### ISSUE THREAD

**Issue by warlof** [eveseat/seat#612]
During the use of SeAT, Here is the problem we encountered

We have PVP, ratting, mining split into 3 different corp in null-sec. (around 600 keys)

I tweak the keys update schedule to every 4 hours. Each run takes about 40 minutes to run.
( for PVP corp to update kill-mail and ratting TAX, but for mining corp 4 hours interval is a bit too short)

**schedule**
I hope there could be a update schedule table for key(s) like groups 
eg. (group A run every hour, group B run every 4 hours and group C run every day)

- this will save resources on update "useless" keys
- If possible constraint keys detail  ( such as update kill-mail every hour and update clone status every week etc.)

sources from eveseat/seat#208

**Comment by rock5917** [comment]
We have two issues with the scheduler here. I would like to see both on future updates but I would like to be clear that they are not the same. The issue #612 it's a quality of life improvement and until we have this update no data can be lost because of it. In the other hand with the issue #626, we have a security problem because if the pilot sends and delete an evemail before the server update that data will be gone.  With that in mind, a cron job with updates on evemails only will help decrease the potential of a security breach and data lost because of a longer delay between cron jobs.

**Comment by leonjza** [comment]
I think this is actually a really simple thing to solve. We have a command that let's you dispatch an [arbitrary job class](https://github.com/eveseat/console/blob/master/src/Commands/Esi/Dispatch.php), but requires the character/token id for authed stuff. A quick middle ground could be to just add a job that follows a similar pattern to the normal updaters, but is limited to a single job class. That way you can schedule a crontab for any custom stuff you may want.

**Comment by warlof** [comment]
Both are targetting the same thing : beeing able to schedule jobs in a more granular way.

This is the reason why I close 626 => centralizing stuff requesting to get a more handy scheduler 😉

Except that, you will always face to cache, so there will always have a minimum window during which you can miss a mail.

In my opinion, the mail is a context, however, it's relevant for any jobs.

**Comment by warlof** [comment]
It has been sorted with buckets since eveapi@4.8.0 😊

https://docs.eveseat.net/admin_guides/buckets

Otherwise, more commands exists since SeAT 4 giving more flexibility regarding contracts, killmails and notifications.
