### ISSUE TITLE
No permission on mail timeline

### ISSUE THREAD

**Issue by lk77** [eveseat/seat#614]
* **Problem**: Mail timeline  is accessible to every users
* **Expected**: Mail timeline should be accessible only to admins
* **Version Info**: 

| Package Name  | Local Version | Latest Github |
|---------------|---------------|---------------|
| Api           | 3.0.8         | 3.0.8         |
| Console       | 3.0.5         | 3.0.5         |
| Eveapi        | 3.0.18        | 3.0.20        |
| Notifications | 3.0.6         | 3.0.6         |
| Web           | 3.0.28        | 3.0.28        |
| Services      | 3.0.11        | 3.0.11        |

(running on official docker image)

Hello,

we have an issue, mail timeline is accessible to every user, and we can see personal mails from every user. I don't think it's the correct behaviour. This page should only display mails of the logged-in user, or only be accessible to admins.

thanks.

**Comment by warlof** [comment]
Hi,

this seems to be a role configuration issue more than a security issue since an user who doesn't have `character.mail` permission can't get access to mail he didn't receive.

Please check bellow :
 - the user is not part of a role with `superuser` permission
 - the user is not part of a role with `character.mail` permission with a `all character` affiliation
 - the user is not part of a role with `character.mail` permission without any affiliation

If you need more assistance, please share roles settings to which this user is member.

Also, you're running an outdated version, please consider to update ;)

**Comment by lk77** [comment]
Hello,

it's not an outdated version, it's the last stable version,
i wait for the release candidate cycle to end to install v4.

Indeed permission character.mail is granted to allow users to access their own mail.

**Comment by warlof** [comment]
It's not what your table show

`eveseat/eveapi` package is using 3.0.18 whereas latest is 3.0.20

Regarding permissions, you don't have to grant a character permission to somebody in order to grant him access to its own stuff. It's by default - you can't prevent an user to get access to its content. The exact same apply to corporation permissions.

**Comment by lk77** [comment]
Perhaps not up to date, but not outdated, two minor versions are not a big deal.

**Comment by warlof** [comment]
Just for reference
using docker, this is the way to use in order to get update : https://eveseat.github.io/docs/admin_guides/docker_admin/#performing-updates

**Comment by lk77** [comment]
yes, to update the docker image to the last version, but composer should update to last version anyway since you are doing a composer update in your starting script.

**Comment by warlof** [comment]
only plugins are updated, core package are relaying to docker images - except if there is an unmet dependency in a plugin.

https://github.com/eveseat/docker-eveseat-app/blob/master/startup.sh#L50-L51
