### ISSUE TITLE
DATABASE - Table 'seat.users' doesn't exist

### ISSUE THREAD

**Issue by frank1210** [eveseat/seat#687]
* **Problem**: _Whats wrong?
After migrating from V3.0 to V4.0 i get the following error when trying to get my database backup:
ERROR 1005 (HY000) at line 6663: Can't create table `seat`.`users` (errno: 150 "Foreign key constraint is incorrectly formed")
If artisan and workers are enabled with debug active this is what i get:
 1- SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.users' doesn't exist (SQL: select * from `users` where `id` = 30 limit 1)
2- (2/3) ExceptionSQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.users' doesn't exist
PDOException
3- SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.users' doesn't exist

System: Ubuntu 16, php 7.3, seat v4.0, apache, mariadb 10.3.7

Command used to get backup:
mysql -u USER -p seat < backup.sql

**Comment by Crypta-Eve** [comment]
Ok, the title is a bit misleading.. The issue isnt that the the table doesnt exist. That is the symptom. The problem is that your backup import failed so of course your table wont exist. Now if it is the problem I am thinking of, it is due to a character encoding mismatch between the backup and the target database. 

My recommended solution is as follows:

1. Access the mariadb shell (for docker use `docker-compose exec -T mariadb sh -c 'exec mysql "$MYSQL_DATABASE" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"'`
2. `DROP DATABASE SEAT`
3. `CREATE DATABASE SEAT`
4. Leave the DB shell and restore your backup as per normal.

**Comment by warlof** [comment]
Hi,

When do you have this message ?

**Comment by frank1210** [comment]
Hello,

I got it after trying to log in with my account

**Comment by warlof** [comment]
I'm afraid either your backup or your upgrade is still corrupted.

- did you update to latest 3.0.x version from all packages before starting the upgrade of 4.0.x ?
- did you encounter any error while either running the backup or restoring it ?
- did you encounter any error during the upgrade flow ?
- did you use any third party package ?
