### ISSUE TITLE
Prescreening capabilities and Squad functionality expansion

### ISSUE THREAD

**Issue by juststevesengir** [eveseat/seat#693]
Under the Settings>Access Management>Roles> Character and Corporation Permission Limits
Can these be expanded to include Squads? Or expanded to prevent access to specific corps?

Squads>"SquadName"> Edit> Filters>
Can we get a Skill Level" option added to the "Skill" "Is" filter?

**Comment by warlof** [comment]
Squads have not be designed to be managed by roles.
They supposed to be used to add automation on your roles management.

Inverse filter must be took in consideration since it appears a lot of people would have them. The new permissions system may reduce a bit the involved code complexity.

As per skill level filter, it's doable
