### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by SergeyAB** [eveseat/seat#695]
Hello!

* **Problem**: Bookmarks doesn't update.
* **Expected**: Disable/hide/remove tabs and tasks for these API endpoints. 
* **Logs / Screenshots / Proof**: 
* https://developers.eveonline.com/blog/article/temporary-blackout-of-esi-bookmarks
* https://github.com/esi/esi-issues/blob/master/changelog.md

I tried to use 
https://esi.evetech.net/ui/#/Bookmarks/get_characters_character_id_bookmarks_folders
https://esi.evetech.net/ui/#/Bookmarks/get_characters_character_id_bookmarks
..., but server returns no data for both.

**Comment by Crypta-Eve** [comment]
Correct that the current bookmarks systems is not available on ESI.

As to your issue, I dont think the jobs are run anymore but will have to check that...

And what about historical data, if the tab was removed then the existing data many people have would not be viewable.

**Comment by SergeyAB** [comment]
> And what about historical data, if the tab was removed then the existing data many people have would not be viewable.

I agree. If I have no data not mean that no one have no data :)

**Comment by warlof** [comment]
Bookmark jobs is still running.

However, since blackout, all ESI bookmarks endpoints are returning an empty array. This prevent application to crash, but we non longer be able to pull/update anything at this stage.

CCP seems not working a lot on ESI lastly, a bit more on SSO part though and we don't know when that thing will be fixed.

Removing unused tabs can save some space, but that would need a bit more input from the community first :)

**Comment by TaintedSoulz** [comment]
I would be up for hiding the tab and disabling the jobs until the bookmarks esi endpoint is functioning again. That way people aren't thinking that its still working if it exists on the character or corp pages.

**Comment by warlof** [comment]
Bookmarks feature will be removed from console, eveapi and web packages with this week roll up.
