### ISSUE TITLE
Help wanted / Killmails & Tokens Notifications

### ISSUE THREAD

**Issue by muzixa** [eveseat/seat#776]
Hi.
Im doing categorized notifications for different discord channels.
Already checked squad & characters notifications and it works fine.
But no killmails & tokens notifications and

Using slack, maybe there is some trick? 
It's looks like this was trying add characters & corporations, doesn't help

![image](https://user-images.githubusercontent.com/2127645/110247961-cfdeee80-7f7f-11eb-9784-69d538d68c73.png)
![image](https://user-images.githubusercontent.com/2127645/110248005-0caae580-7f80-11eb-844a-d0b4133674d1.png)

**Comment by warlof** [comment]
tokens are only track for the following events :
 - a token is removed => this is only done by core when its access is denied by ESI due to invalidated token
 - a token is restored => this is done after the first one occured AND user reapply (tldr: relink the character)

you need a killmail attached to a character to spawn a notification.
only killmails with less than 3 600 seconds old will be sent - this is to avoid spam when you setup notification on an existing database

**Comment by muzixa** [comment]
Thanks, one more question.
What happens by default if token in invalid, is character automaticaly lose his squads, roles etc,?

**Comment by muzixa** [comment]
More tests:
If character delete esi by himself from ccp 3rd party management page, he losing the squads/roles etc.
If seat admin delete user he he losing squads, roles but not discord roles.

But will test more tomorrow.

**Comment by muzixa** [comment]
Can be closed, all works fine, just some delay
