### ISSUE TITLE
Feature Request - Radar Chart scale by skill impact

### ISSUE THREAD

**Issue by Prosth** [eveseat/seat#854]
Opening issue on request of Warlof Tutsimo on SeAT Discord.

As a player, I want: 1) the skills radar chart to portray which areas players have expertise in, and 2) to calibrate the size on the chart to the strength of those skills.

1) Skills are sorted alphabetically, instead of by parent discipline. This leads to very spiky charts that do not clearly convey area of expertise. If skills were grouped by discipline (i.e. Shields, Armor, and Gunnery under 'Combat' on the lower left quadrant), the chart would at a glance more clearly convey a player's activity focus. This is useful for corporations understanding their strengths, and filling expertise holes.

2) Skill category strength on the chart is relative to the proportion of trained skills versus total available skills. As a result, if I am trained more highly in one category that has a lot of skills, against low training in a category that has fewer skills, I will appear to be _more_ skilled on the latter than the former. An example of this:
![01](https://user-images.githubusercontent.com/12942279/148250755-22cf4665-b581-42f0-9af1-bc52f98910d5.png)

At a glance, you may takeaway that I am moderately trained in missile use, and minimally trained in gunnery. In fact, the opposite is true; I have nearly double the skillpoints in gunnery, but there are far more overall gunnery skills, shrinking the apparent percentage.

Cheers. You make a really cool app.

**Comment by veteranmina** [comment]
Maybe an idea, have a tabbed(option control) in that section where default it shows this "categorically" grouped. If further detail is wanted they could switch to the other view that is currently produced.

**Comment by warlof** [comment]
Yeah, this is also what I think.
We can design two tab, with a chart in each of them.

Can be a new feature for SeAT 5 :)

**Comment by warlof** [comment]
Hi,

While working on skill page redesign for SeAT 5, I figure it could also be tied to this issue.
This is the current mockup :

![image](https://user-images.githubusercontent.com/648753/149219269-f5153de6-fb72-4f87-b262-af649257192b.png)

What you asked for is the new Profile doughnut which seems more relevant than a radar.
Since I used to be polyvalent, it's near to be perfectly balanced, however, it trully show character trend 😂 

![image](https://user-images.githubusercontent.com/648753/149219762-97a65c0d-f518-474e-9c73-005d8ddcded5.png)

![image](https://user-images.githubusercontent.com/648753/149219900-fea3ce99-0adc-40df-bd94-181cdb71f5a8.png)

All those metrics are based on the following split :

![image](https://user-images.githubusercontent.com/648753/149220355-b95e9549-e7bf-468c-853a-e3af05261b99.png)

![image](https://user-images.githubusercontent.com/648753/149220752-a45019b2-6913-478b-a719-d6d8ca01e6fa.png)

However, now, I find the old coverage radar almost useless since we got those stats under category names.
I wonder what could replace it. I tried a skill queue chart without success - there are too much data to be properly rendered.

**Comment by Prosth** [comment]
Looks great!
