### ISSUE TITLE
the role of the old corporation is retained for a time after the change of corporation

### ISSUE THREAD

**Issue by vlvavan** [eveseat/seat#879]
caught an interesting bug
if the character had the role of Director in the corporation from which he left and immediately entered another, then the seat may consider that he is a Director in the new corporation. Apparently, the Roles and Corporations are not updated at the same time, which leads to the fact that he can get into the squad and get access to the seat, team speech and discord as a director.

for this, this member must be previously registered in a seat with another corporation

**Comment by vlvavan** [comment]
for this, this member must be previously registered in a seat with another corporation

**Comment by vlvavan** [comment]
this seems to be a problem with the ESI, since this is repeated in other services

**Comment by recursivetree** [comment]
I guess we could remove roles when a corporation change is detected and block roles from being stored until the ESI cache expires. If ESI character affiliations and roles are on different caches which don't get invalidated at the same time, it might be worth to report it to CCP and other devs, since it is likely that it will happen to others too.

**Comment by recursivetree** [comment]
On another note, it it possible to hide this issue? I guess it is somewhat of a serious security issue

**Comment by vlvavan** [comment]
it took about 18 hours for the roles to update
