### ISSUE TITLE
SeAT 5.0 asset search issue

### ISSUE THREAD

**Issue by he11fireUA** [eveseat/seat#907]
* **Problem**: _The character assets tab does not work correctly; it does not search for existing assets. 
* **Expected**: _Conventionally, I have a vargur, but when I open my character, the assets tab, I don’t see it, etc.In addition, in the Horizon logs there are a lot of failed tasks on assets
* **Logs / Screenshots / Proof**:
```
Illuminate\Queue\MaxAttemptsExceededException: Seat\Eveapi\Jobs\Assets\Character\Assets has been attempted too many times. in /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/MaxAttemptsExceededException.php:24
--
Stack trace:
#0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(785): Illuminate\Queue\MaxAttemptsExceededException::forJob()
#1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(519): Illuminate\Queue\Worker->maxAttemptsExceededException()
#2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts()
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\Queue\Worker->process()
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\Queue\Worker->runJob()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\Queue\Worker->daemon()
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Console\WorkCommand->runWorker()
#7 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\Container\Container->call()
#14 /var/www/seat/vendor/symfony/console/Command/Command.php(326): Illuminate\Console\Command->execute()
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\Component\Console\Command\Command->run()
#16 /var/www/seat/vendor/symfony/console/Application.php(1096): Illuminate\Console\Command->run()
#17 /var/www/seat/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/seat/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\Component\Console\Application->run()
#20 /var/www/seat/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#21 {main}
```

* **Version Info**: 

| | | |
| -------- | --- | ----- |
| eveseat | api | 5.0.0 |
| eveseat | eseye | 3.0.1 |
| eveseat | eveapi | 5.0.11 |
| eveseat | notifications | 5.0.8 |
| eveseat | services | 5.0.7 |
| eveseat | web | 5.0.9 |

I added several screenshots (in one of them I was looking for X-type modules of which I have literally dozens, but the search does not show them).
P.S. This is my first time writing something here because if I did something bad or inconvenient for others, please tell me so

![16VvShN9PA](https://github.com/eveseat/seat/assets/67373168/bf946eab-ae3a-4745-8f35-1fb24578c3bc)
![24k7csiGYV](https://github.com/eveseat/seat/assets/67373168/c0fead00-7dc9-4eaa-b77c-426368168024)
![GNO6nyjBpU](https://github.com/eveseat/seat/assets/67373168/18e45878-654e-46ef-83b4-5f35fe3daa85)
![N1fr52uO3R](https://github.com/eveseat/seat/assets/67373168/ea6bb13a-20f5-43f7-a373-ae9043a96514)

**Comment by alexaroth** [comment]
Running into the same issue as well, asset search is very flaky, it doesn't show a lot of items that should ge there. If I click the refresh button top right of the search tab, it runs a asset query job and then I have more items that it's searching from. I can keep doing that and it populates more and more items but sometimes it can even lose items

**Comment by Lynnezra** [comment]
Also I wanted to say, did you guys notice the tracking on the corp page. Searching for a character's name inside of tracking gives you an error! -DataTables warning: table id=dataTableBuilder - Ajax error. For more information about this error, please see https://datatables.net/tn/7  
PS: I use docker to build it.

**Comment by he11fireUA** [comment]
I generally identified this problem as follows. I have a squad with capital ships. And its entry conditions are the following - to have a calibration of 4 and the presence of capital. For the test now this is nidhoggur, because several members of the corporation have it. Based on this squad, people are given a role in teamspeak. And now we’re sitting in team talk and the seat will either give the role or take it away. Apparently assets are indexed, they are lost and the role is taken away. I checked this. When I lose the role of capital in the team speak in the seat, my nidhoggur is not found in the asset search

**Comment by Crypta-Eve** [comment]
I believe this will be closed by https://github.com/eveseat/eveapi/pull/402

**Comment by tmas** [comment]
I suspect this error I found in my logs is related to this issue:

[2024-05-22 20:07:00] local.ERROR: count(): Argument #1 ($value) must be of type Countable|array, stdClass given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, stdClass given at /var/www/seat/vendor/softcreatr/jsonpath/src/Filters/SliceFilter.php:17)
[stacktrace]
#0 /var/www/seat/vendor/softcreatr/jsonpath/src/JSONPath.php(51): Flow\\JSONPath\\Filters\\SliceFilter->filter()
#1 /var/www/seat/vendor/eveseat/eveapi/src/Mapping/DataMapping.php(66): Flow\\JSONPath\\JSONPath->find()
#2 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Character/Assets.php(114): Seat\\Eveapi\\Mapping\\DataMapping::make()
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets->Seat\\Eveapi\\Jobs\\Assets\\Character\\{closure}()
#4 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Character/Assets.php(103): Illuminate\\Support\\Collection->each()
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets->Seat\\Eveapi\\Jobs\\Assets\\Character\\{closure}()
#6 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Assets/Character/Assets.php(101): Illuminate\\Support\\Collection->each()
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Seat\\Eveapi\\Jobs\\Assets\\Character\\Assets->handle()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Middleware/WithoutOverlapping.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Queue\\Middleware\\WithoutOverlapping->handle()
#20 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenVersion.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckTokenVersion->handle()
#22 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckTokenScope.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckTokenScope->handle()
#24 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckEsiRouteStatus.php(80): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckEsiRouteStatus->handle()
#26 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckServerStatus.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckServerStatus->handle()
#28 /var/www/seat/vendor/eveseat/eveapi/src/Jobs/Middleware/CheckEsiRateLimit.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Seat\\Eveapi\\Jobs\\Middleware\\CheckEsiRateLimit->handle()
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#39 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#46 /var/www/seat/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#48 /var/www/seat/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#49 /var/www/seat/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#50 /var/www/seat/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#51 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#52 /var/www/seat/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#53 {main}
"}

My guess is that loading character assets from ESI broke at some point, and the missing assets people are seeing are assets that they acquired ingame after the last successful asset update from ESI. It's hard to say with certainty if this is the same issue or not, though, because the job-related error posted in the original issue only shows that the job failed and not why it failed.

If it matters, I encountered the error I posted on a fresh SeAT instance. I followed all installation instructions with one small change, installing php8.3-* packages instead of php8.2-* packages because the software requirements have been updated to show that the required PHP version is now ^8.3.

**Comment by tehraven** [comment]
@he11fireUA can you confirm this is all fixed using the latest versions?

**Comment by he11fireUA** [comment]
every test which i do was successfully! Great job, thx!
