### ISSUE TITLE
Mariadb performance issues - missing indexes

### ISSUE THREAD

**Issue by rapenne-s** [eveseat/seat#914]
* **Problem**:

My SeAT 4.3.0 instance got very slow daily, always at the same time. I figured that it was related to the task treelib:esi:prices:update

After digging a bit, there was an issue with this query

```
MariaDB [seat]> show FULL processlist;
+-------+------+------------------+------+---------+------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| Id    | User | Host             | db   | Command | Time | State        | Info                                                                                                                                                                  | Progress |
+-------+------+------------------+------+---------+------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| 24747 | seat | 172.23.0.6:34116 | seat | Sleep   |    9 |              | NULL                                                                                                                                                                  |    0.000 |
| 24760 | seat | 172.23.0.6:58230 | seat | Execute | 2433 | Sending data | select type_id, MIN(price) as sell_price from `market_orders` where `is_buy_order` = ? group by `type_id` order by `market_orders`.`order_id` asc limit 1000 offset 0 |    0.000 |
| 24861 | seat | 172.23.0.6:57516 | seat | Execute | 1473 | Sending data | select type_id, MIN(price) as sell_price from `market_orders` where `is_buy_order` = ? group by `type_id` order by `market_orders`.`order_id` asc limit 1000 offset 0 |    0.000 |
| 24946 | seat | 172.23.0.6:60314 | seat | Execute |  512 | Sending data | select type_id, MIN(price) as sell_price from `market_orders` where `is_buy_order` = ? group by `type_id` order by `market_orders`.`order_id` asc limit 1000 offset 0 |    0.000 |
```

This query is taking way too long, the beefy server is crawling under i/o waits due to the database doing this query, it was taking 5 painful hours to finish with the scheduled task, every day.

I tried to run `mysqlcheck --autorepair --optimize` to run OPTIMIZE on each innodb tables, this did not help much. (solution below).

* **Expected**:

no performance problem

* **Solution**:

I solved it by creating 2 indexes:

```
create index idx_price on market_orders(price);
create index idx_is_buy_order on market_orders(is_buy_order);
```

Now, these requests take 5 seconds to give a result. I'm not sure both indexes are required though.

I don't have a PR because I don't know where indexes are handled, and I don't know if both are required, it may be overkill to have both, I expect the index on `is_buy_order` to be useless as it'a s boolean. Some litterature about indexes for booleans https://funivan.com/post/boolean-field-index/

**Comment by recursivetree** [comment]
Thanks for tracking this down. It is very well possible that some indexes are missing, especially ones that only have an impact once a day.

Fixing it might need some thoughts though:
In SeAT 4, market orders are not handled by the seat core, but instead by the `recursivetree/seat-treelib` plugin. 
In SeAT 5, the market order functionality of treelib got merged into the core. The tables were taken over one to one, so migrations between seat 4 treelib and seat 5 eveapi must be kept in sync so it is possible to upgrade from seat 4 to 5.

Does the performance issue also happen on seat 5 for you? Then opening an issue here is fine. Otherwise please open an issue over here: https://github.com/eveseat-plugins/seat-treelib. While support for seat 4 has more or less ended, I think I could make an exception here since it is probably a rather small fix.

As for writing a PR: In seat 4, you'd have to write a database migration in here: https://github.com/eveseat-plugins/seat-treelib/tree/seat-4.x/src/database/migrations
and in seat 5 in here: https://github.com/eveseat/eveapi/tree/master/src/database/migrations
The laravel docs are relatively good at explaining how to write migrations: https://laravel.com/docs/10.x/migrations

**Comment by rapenne-s** [comment]
thanks, I close this issue, it might be helpful to someone in the same situation as mine. I didn't migrate to SeAT 5 yet, but I'll keep in mind that I may have to delete the indexes for the migration. This will give me the opportunity to see if I encounter the issue on SeAT 5 once there.
